### ISSUE TITLE
Progress Plugin Invalid Options when starting Angular project using now-ui-kit-pro-angular-v1.1.0

### ISSUE THREAD

**Issue by geraertsf** [creativetimofficial/ct-now-ui-kit-pro-angular#6] opened 2018-12-30 13:16 UTC
Hi, 

# Description

I try to launch the application using ng serve.

I've got the following error:

```
yarn run v1.12.1
$ ng serve
Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/schema-utils/src/validateOptions.js:31:11)
    at new ProgressPlugin (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/webpack/lib/ProgressPlugin.js:90:3)
    at Object.getCommonConfig (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:123:27)
    at BrowserBuilder.buildWebpackConfig (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/src/browser/index.js:74:31)
    at DevServerBuilder.buildWebpackConfig (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:111:46)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:38:40)
    at MergeMapSubscriber._tryNext (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/Users/geraertsf/work/perso/style/now-ui-kit-pro-angular-v1.1.0/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
error Command failed with exit code 1.
```

Could you have a look ?

Many thanks.

# Environment/Tools

```
Mac Os 10.14.2 (18C54)
Node 11.2.0
Yarn 1.12.1
```

**Comment by chelaruc** [comment] 2019-01-27 11:04
@midryndhil try to run this command inside your project: `npm i --save webpack`
Let me know if it works.

**Comment by dmbjsn** [comment] 2019-02-02 07:50
Hi, I just bought this including premium support extension. I have the same problem, tried installing webpack, didn't change anything. Upgraded to latest node and npm. How can I get to work?

**EDIT** Duplicate of https://github.com/angular/angular-cli/issues/12866 Please fix, so we don't need the devDependencies workaround

**Comment by tej-rana** [comment] 2019-02-06 23:18
Ok so the only thing that fixed this issue was to add this specific version of webpack as dev dependency.
`"webpack": "4.24.0"`

**Comment by chelaruc** [comment] 2019-02-11 13:54
@tesnep solved this issue

**Closed as completed by chelaruc** 2019-02-11 13:54 UTC
